### ISSUE TITLE
Create release

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.browserpage#5]
Can I get a release or the necessary rights on PyPI.
I'm `icemac` there.

**Comment by mgedmin** [comment]
I don't have any PyPI rights to give you, but @jamadden has.

**Comment by jamadden** [comment]
I've got `fullrelease` pushing 4.3 to PyPI in the background. In the meantime, what's your PyPI username again @icemac?

**Comment by jamadden** [comment]
D'oh. I didn't read the second line. Sorry. Granting now.

**Comment by mgedmin** [comment]
(My comment was an oblique hint that I would like to have PyPI access too, just in case.  Cc: @jamadden ;)

**Comment by jamadden** [comment]
Done! Sorry I didn't pick up on that.

**Comment by icemac** [comment]
@jamadden Thank you.
